version: '3'
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - .:/usr/src/app
    command: npm start

  frontend:
    build: ./my-dog-app
    ports:
      - "3001:80"
    volumes:
      - ./my-dog-app:/app
      - /app/node_modules